version: '3.8'

services:
  # Piazza API Application
  piazza-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piazza-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Use MongoDB Atlas (your current setup)
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: ${JWT_EXPIRE}
    networks:
      - piazza-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - mongodb
    # For production, use MongoDB Atlas instead of local MongoDB
    # Comment out 'depends_on: mongodb' when using Atlas

  # Local MongoDB (Optional - for local development)
  # Comment this out when using MongoDB Atlas in production
  mongodb:
    image: mongo:7.0
    container_name: piazza-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin123}
      MONGO_INITDB_DATABASE: chamaleon
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      - piazza-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # MongoDB Express (Web UI for MongoDB - Optional)
  mongo-express:
    image: mongo-express:latest
    container_name: piazza-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-admin123}
      ME_CONFIG_MONGODB_URL: mongodb://admin:${MONGO_ROOT_PASSWORD:-admin123}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-admin123}
    networks:
      - piazza-network
    depends_on:
      - mongodb

networks:
  piazza-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
  mongodb-config:
    driver: local
